pasos_por_episodio: 35
alpha1: 10.0
alpha2: 30.0
alpha3: 5.0
alpha4: 2.0
sigma: 100
verboso: False
velocidad_blob: 0
num_generaciones: 15
posicion_inicial: null 
#posicion_inicial: {'x': -1000.0, 'y': 39, 'z': -400.0 }
guarda_genoma: True
genoma_archivo: "P2/genomas/genoma_9.pkl"
